# Generated by Django 3.2.12 on 2022-02-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tur nomi')),
                ('description', models.TextField(verbose_name="Tur haqida ma'lumot")),
                ('image', models.ImageField(upload_to='', verbose_name='Asosiy rasm')),
            ],
            options={
                'verbose_name': 'Turistlar uchun Tur',
                'verbose_name_plural': 'Turistlar uchun Turlar',
            },
        ),
        migrations.CreateModel(
            name='TourShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='', verbose_name='Tur rasmlari')),
                ('name', models.CharField(max_length=50, verbose_name='Rasm nomi')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tour', verbose_name='Tur')),
            ],
            options={
                'verbose_name': 'Tur uchun rasm',
                'verbose_name_plural': 'Tur uchun rasmlar',
            },
        ),
    ]
